name: IntroductionToML
channels:
  - conda-forge
  - default
dependencies:
  - jupytext
  - jupyterlab
  - python
  - numpy
  - matplotlib-base
  - ipympl
  - torch
  - torchvision
  - efficientnet_pytorch
